### ISSUE TITLE
Error: spawn xinit ENOENT when pushing website to frame.

### ISSUE THREAD

**Issue by pierredepaz** [OpenframeProject/Openframe#36]
After a fresh install of Openframe on a Raspberry Pi 3 running Stretch Lite, I wanted to push a website to my frame and get this:

```
events.js:160
   throw er: //Unhandled 'error' event

Error: spawn xinit ENOENT
   at exports._errnoException (util.js:1022:11)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
   at onErrorNT (internal/child_process.js:359:16)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any idea where it could be coming from? I tried different websites and rebooting.

**Comment by jmwohl** [comment]
We haven't had a chance to get things working properly on Stretch, but chances are websites won't work on Stretch Lite because it doesn't have all of the desktop environment packages installed, which 'website' artworks need in order to run. Websites are launched via xinit, part of the X window system.
