### ISSUE TITLE
Debug-errors on changing artwork 

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe#66]
The transitions between artworks on the screen seem fine but with `DEBUG=*` I get the following errors on the console.

Tested on current master with Pi3B.

After website:
```
    openframe:frame_controller endArt +2ms
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 95 requests (94 known processed) with 0 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 973 requests (973 known processed) with 0 events remaining.
[6323:6323:1012/130642.055488:ERROR:x11_util.cc(109)] X IO error received (X server probably went away)
[6257:6257:1012/130642.065691:ERROR:chrome_browser_main_extra_parts_x11.cc(62)] X IO error received (X server probably went away)
  openframe:frame_controller Error: Command failed: pkill -f X
  openframe:frame_controller 
  openframe:frame_controller     at ChildProcess.exithandler (child_process.js:206:12)
  openframe:frame_controller     at emitTwo (events.js:106:13)
  openframe:frame_controller     at ChildProcess.emit (events.js:191:7)
  openframe:frame_controller     at maybeClose (internal/child_process.js:877:16)
  openframe:frame_controller     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) +118ms
  openframe:frame_controller startArt +27ms
```

After image:
```
  openframe:frame_controller endArt +1ms
  openframe:frame_controller Error: Command failed: sudo pkill -f glslViewer
  openframe:frame_controller 
  openframe:frame_controller     at ChildProcess.exithandler (child_process.js:206:12)
  openframe:frame_controller     at emitTwo (events.js:106:13)
  openframe:frame_controller     at ChildProcess.emit (events.js:191:7)
  openframe:frame_controller     at maybeClose (internal/child_process.js:877:16)
  openframe:frame_controller     at Socket.<anonymous> (internal/child_process.js:334:11)
  openframe:frame_controller     at emitOne (events.js:96:13)
  openframe:frame_controller     at Socket.emit (events.js:188:7)
  openframe:frame_controller     at Pipe._handle.close [as _onclose] (net.js:498:12) +589ms
  openframe:frame_controller startArt +8ms
  openframe:processing copy sketch to parent folder +
```

After video:
```
 openframe:frame_controller endArt +0ms
  process_manager child 6927 closing code: null +135ms
  openframe:frame_controller Error: Command failed: sudo pkill -f omxplayer
  openframe:frame_controller 
  openframe:frame_controller     at ChildProcess.exithandler (child_process.js:206:12)
  openframe:frame_controller     at emitTwo (events.js:106:13)
  openframe:frame_controller     at ChildProcess.emit (events.js:191:7)
  openframe:frame_controller     at maybeClose (internal/child_process.js:877:16)
  openframe:frame_controller     at Socket.<anonymous> (internal/child_process.js:334:11)
  openframe:frame_controller     at emitOne (events.js:96:13)
  openframe:frame_controller     at Socket.emit (events.js:188:7)
  openframe:frame_controller     at Pipe._handle.close [as _onclose] (net.js:498:12) +25ms
  openframe:frame_controller startArt +3ms
```

**Comment by jvolker** [comment]
Still an issue with v0.4.12
